version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    links:
      - php72:fpm

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3366:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
      - ./log/mysql/:/var/log/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "docker"
      MYSQL_DATABASE: "docker_label"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6369:6379"

  php72:
      container_name: php72
      build: ./php/php72/
      expose:
        - "9000"
      volumes:
        - ./www/:/var/www/html/:rw
        - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
        - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        - ./log/php-fpm/:/var/log/php-fpm/:rw
      links:
        - mysql:mysql
        - redis:redis
